version: '3.8'

services:
  postgres-new:
    image: postgres:16-alpine
    container_name: ecom-be-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra-network

  redis:
    image: redis:7-alpine
    container_name: ecom-be-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra-network

volumes:
  postgres_data_new:
  redis_data:


networks:
  infra-network:
    driver: bridge
